server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index boq-dashboard.html index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location /api/ {
        proxy_pass http://oce-core:8081;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
